import { type HttpStatusCode, httpStatusCodes } from "../status/index.js";

export const httpPhrases = {
	ACCEPTED: "Accepted",
	BAD_GATEWAY: "Bad Gateway",
	BAD_REQUEST: "Bad Request",
	CONFLICT: "Conflict",
	CONTINUE: "Continue",
	CREATED: "Created",
	EXPECTATION_FAILED: "Expectation Failed",
	FAILED_DEPENDENCY: "Failed Dependency",
	FORBIDDEN: "Forbidden",
	GATEWAY_TIMEOUT: "Gateway Timeout",
	GONE: "Gone",
	HTTP_VERSION_NOT_SUPPORTED: "HTTP Version Not Supported",
	IM_A_TEAPOT: "I'm a teapot",
	INSUFFICIENT_SPACE_ON_RESOURCE: "Insufficient Space on Resource",
	INSUFFICIENT_STORAGE: "Insufficient Storage",
	INTERNAL_SERVER_ERROR: "Internal Server Error",
	LENGTH_REQUIRED: "Length Required",
	LOCKED: "Locked",
	METHOD_FAILURE: "Method Failure",
	METHOD_NOT_ALLOWED: "Method Not Allowed",
	MOVED_PERMANENTLY: "Moved Permanently",
	MOVED_TEMPORARILY: "Moved Temporarily",
	MULTI_STATUS: "Multi-Status",
	MULTIPLE_CHOICES: "Multiple Choices",
	NETWORK_AUTHENTICATION_REQUIRED: "Network Authentication Required",
	NO_CONTENT: "No Content",
	NON_AUTHORITATIVE_INFORMATION: "Non Authoritative Information",
	NOT_ACCEPTABLE: "Not Acceptable",
	NOT_FOUND: "Not Found",
	NOT_IMPLEMENTED: "Not Implemented",
	NOT_MODIFIED: "Not Modified",
	OK: "OK",
	PARTIAL_CONTENT: "Partial Content",
	PAYMENT_REQUIRED: "Payment Required",
	PERMANENT_REDIRECT: "Permanent Redirect",
	PRECONDITION_FAILED: "Precondition Failed",
	PRECONDITION_REQUIRED: "Precondition Required",
	PROCESSING: "Processing",
	EARLY_HINTS: "Early Hints",
	UPGRADE_REQUIRED: "Upgrade Required",
	PROXY_AUTHENTICATION_REQUIRED: "Proxy Authentication Required",
	REQUEST_HEADER_FIELDS_TOO_LARGE: "Request Header Fields Too Large",
	REQUEST_TIMEOUT: "Request Timeout",
	REQUEST_TOO_LONG: "Request Entity Too Large",
	REQUEST_URI_TOO_LONG: "Request-URI Too Long",
	REQUESTED_RANGE_NOT_SATISFIABLE: "Requested Range Not Satisfiable",
	RESET_CONTENT: "Reset Content",
	SEE_OTHER: "See Other",
	SERVICE_UNAVAILABLE: "Service Unavailable",
	SWITCHING_PROTOCOLS: "Switching Protocols",
	TEMPORARY_REDIRECT: "Temporary Redirect",
	TOO_MANY_REQUESTS: "Too Many Requests",
	UNAUTHORIZED: "Unauthorized",
	UNAVAILABLE_FOR_LEGAL_REASONS: "Unavailable For Legal Reasons",
	UNPROCESSABLE_ENTITY: "Unprocessable Entity",
	UNSUPPORTED_MEDIA_TYPE: "Unsupported Media Type",
	USE_PROXY: "Use Proxy",
	MISDIRECTED_REQUEST: "Misdirected Request",
} as const;

export type HttpPhraseName = keyof typeof httpPhrases;
export type HttpPhrase = (typeof httpPhrases)[HttpPhraseName];

export const httpPhrasesByStatusCode: Record<HttpStatusCode, HttpPhrase> = {
	[httpStatusCodes.ACCEPTED]: httpPhrases.ACCEPTED,
	[httpStatusCodes.BAD_GATEWAY]: httpPhrases.BAD_GATEWAY,
	[httpStatusCodes.BAD_REQUEST]: httpPhrases.BAD_REQUEST,
	[httpStatusCodes.CONFLICT]: httpPhrases.CONFLICT,
	[httpStatusCodes.CONTINUE]: httpPhrases.CONTINUE,
	[httpStatusCodes.CREATED]: httpPhrases.CREATED,
	[httpStatusCodes.EXPECTATION_FAILED]: httpPhrases.EXPECTATION_FAILED,
	[httpStatusCodes.FAILED_DEPENDENCY]: httpPhrases.FAILED_DEPENDENCY,
	[httpStatusCodes.FORBIDDEN]: httpPhrases.FORBIDDEN,
	[httpStatusCodes.GATEWAY_TIMEOUT]: httpPhrases.GATEWAY_TIMEOUT,
	[httpStatusCodes.GONE]: httpPhrases.GONE,
	[httpStatusCodes.HTTP_VERSION_NOT_SUPPORTED]:
		httpPhrases.HTTP_VERSION_NOT_SUPPORTED,
	[httpStatusCodes.IM_A_TEAPOT]: httpPhrases.IM_A_TEAPOT,
	[httpStatusCodes.INSUFFICIENT_SPACE_ON_RESOURCE]:
		httpPhrases.INSUFFICIENT_SPACE_ON_RESOURCE,
	[httpStatusCodes.INSUFFICIENT_STORAGE]: httpPhrases.INSUFFICIENT_STORAGE,
	[httpStatusCodes.INTERNAL_SERVER_ERROR]: httpPhrases.INTERNAL_SERVER_ERROR,
	[httpStatusCodes.LENGTH_REQUIRED]: httpPhrases.LENGTH_REQUIRED,
	[httpStatusCodes.LOCKED]: httpPhrases.LOCKED,
	[httpStatusCodes.METHOD_FAILURE]: httpPhrases.METHOD_FAILURE,
	[httpStatusCodes.METHOD_NOT_ALLOWED]: httpPhrases.METHOD_NOT_ALLOWED,
	[httpStatusCodes.MOVED_PERMANENTLY]: httpPhrases.MOVED_PERMANENTLY,
	[httpStatusCodes.MOVED_TEMPORARILY]: httpPhrases.MOVED_TEMPORARILY,
	[httpStatusCodes.MULTI_STATUS]: httpPhrases.MULTI_STATUS,
	[httpStatusCodes.MULTIPLE_CHOICES]: httpPhrases.MULTIPLE_CHOICES,
	[httpStatusCodes.NETWORK_AUTHENTICATION_REQUIRED]:
		httpPhrases.NETWORK_AUTHENTICATION_REQUIRED,
	[httpStatusCodes.NO_CONTENT]: httpPhrases.NO_CONTENT,
	[httpStatusCodes.NON_AUTHORITATIVE_INFORMATION]:
		httpPhrases.NON_AUTHORITATIVE_INFORMATION,
	[httpStatusCodes.NOT_ACCEPTABLE]: httpPhrases.NOT_ACCEPTABLE,
	[httpStatusCodes.NOT_FOUND]: httpPhrases.NOT_FOUND,
	[httpStatusCodes.NOT_IMPLEMENTED]: httpPhrases.NOT_IMPLEMENTED,
	[httpStatusCodes.NOT_MODIFIED]: httpPhrases.NOT_MODIFIED,
	[httpStatusCodes.OK]: httpPhrases.OK,
	[httpStatusCodes.PARTIAL_CONTENT]: httpPhrases.PARTIAL_CONTENT,
	[httpStatusCodes.PAYMENT_REQUIRED]: httpPhrases.PAYMENT_REQUIRED,
	[httpStatusCodes.PERMANENT_REDIRECT]: httpPhrases.PERMANENT_REDIRECT,
	[httpStatusCodes.PRECONDITION_FAILED]: httpPhrases.PRECONDITION_FAILED,
	[httpStatusCodes.PRECONDITION_REQUIRED]: httpPhrases.PRECONDITION_REQUIRED,
	[httpStatusCodes.PROCESSING]: httpPhrases.PROCESSING,
	[httpStatusCodes.EARLY_HINTS]: httpPhrases.EARLY_HINTS,
	[httpStatusCodes.UPGRADE_REQUIRED]: httpPhrases.UPGRADE_REQUIRED,
	[httpStatusCodes.PROXY_AUTHENTICATION_REQUIRED]:
		httpPhrases.PROXY_AUTHENTICATION_REQUIRED,
	[httpStatusCodes.REQUEST_HEADER_FIELDS_TOO_LARGE]:
		httpPhrases.REQUEST_HEADER_FIELDS_TOO_LARGE,
	[httpStatusCodes.REQUEST_TIMEOUT]: httpPhrases.REQUEST_TIMEOUT,
	[httpStatusCodes.REQUEST_TOO_LONG]: httpPhrases.REQUEST_TOO_LONG,
	[httpStatusCodes.REQUEST_URI_TOO_LONG]: httpPhrases.REQUEST_URI_TOO_LONG,
	[httpStatusCodes.REQUESTED_RANGE_NOT_SATISFIABLE]:
		httpPhrases.REQUESTED_RANGE_NOT_SATISFIABLE,
	[httpStatusCodes.RESET_CONTENT]: httpPhrases.RESET_CONTENT,
	[httpStatusCodes.SEE_OTHER]: httpPhrases.SEE_OTHER,
	[httpStatusCodes.SERVICE_UNAVAILABLE]: httpPhrases.SERVICE_UNAVAILABLE,
	[httpStatusCodes.SWITCHING_PROTOCOLS]: httpPhrases.SWITCHING_PROTOCOLS,
	[httpStatusCodes.TEMPORARY_REDIRECT]: httpPhrases.TEMPORARY_REDIRECT,
	[httpStatusCodes.TOO_MANY_REQUESTS]: httpPhrases.TOO_MANY_REQUESTS,
	[httpStatusCodes.UNAUTHORIZED]: httpPhrases.UNAUTHORIZED,
	[httpStatusCodes.UNAVAILABLE_FOR_LEGAL_REASONS]:
		httpPhrases.UNAVAILABLE_FOR_LEGAL_REASONS,
	[httpStatusCodes.UNPROCESSABLE_ENTITY]: httpPhrases.UNPROCESSABLE_ENTITY,
	[httpStatusCodes.UNSUPPORTED_MEDIA_TYPE]: httpPhrases.UNSUPPORTED_MEDIA_TYPE,
	[httpStatusCodes.USE_PROXY]: httpPhrases.USE_PROXY,
	[httpStatusCodes.MISDIRECTED_REQUEST]: httpPhrases.MISDIRECTED_REQUEST,
};

export const getHttpPhrase = (code: HttpStatusCode): HttpPhrase =>
	httpPhrasesByStatusCode[code];

export const getHttpPhraseByName = (name: HttpPhraseName): HttpPhrase =>
	httpPhrases[name];

export const {
	ACCEPTED,
	BAD_GATEWAY,
	BAD_REQUEST,
	CONFLICT,
	CONTINUE,
	CREATED,
	EXPECTATION_FAILED,
	FAILED_DEPENDENCY,
	FORBIDDEN,
	GATEWAY_TIMEOUT,
	GONE,
	HTTP_VERSION_NOT_SUPPORTED,
	IM_A_TEAPOT,
	INSUFFICIENT_SPACE_ON_RESOURCE,
	INSUFFICIENT_STORAGE,
	INTERNAL_SERVER_ERROR,
	LENGTH_REQUIRED,
	LOCKED,
	METHOD_FAILURE,
	METHOD_NOT_ALLOWED,
	MOVED_PERMANENTLY,
	MOVED_TEMPORARILY,
	MULTI_STATUS,
	MULTIPLE_CHOICES,
	NETWORK_AUTHENTICATION_REQUIRED,
	NO_CONTENT,
	NON_AUTHORITATIVE_INFORMATION,
	NOT_ACCEPTABLE,
	NOT_FOUND,
	NOT_IMPLEMENTED,
	NOT_MODIFIED,
	OK,
	PARTIAL_CONTENT,
	PAYMENT_REQUIRED,
	PERMANENT_REDIRECT,
	PRECONDITION_FAILED,
	PRECONDITION_REQUIRED,
	PROCESSING,
	EARLY_HINTS,
	UPGRADE_REQUIRED,
	PROXY_AUTHENTICATION_REQUIRED,
	REQUEST_HEADER_FIELDS_TOO_LARGE,
	REQUEST_TIMEOUT,
	REQUEST_TOO_LONG,
	REQUEST_URI_TOO_LONG,
	REQUESTED_RANGE_NOT_SATISFIABLE,
	RESET_CONTENT,
	SEE_OTHER,
	SERVICE_UNAVAILABLE,
	SWITCHING_PROTOCOLS,
	TEMPORARY_REDIRECT,
	TOO_MANY_REQUESTS,
	UNAUTHORIZED,
	UNAVAILABLE_FOR_LEGAL_REASONS,
	UNPROCESSABLE_ENTITY,
	UNSUPPORTED_MEDIA_TYPE,
	USE_PROXY,
	MISDIRECTED_REQUEST,
} = httpPhrases;
